baseURL: "/"
languageCode: "en-us"

menu:
  main:
    - name: "home"
      url: "/"
      weight: 1
    - name: "blog"
      url: "blog/"
      weight: 5
    - name: "projects"
      url: "projects/"
      weight: 7
    - name: "now"
      url: "now/"
      weight: 9

params:
  author: "Francisco Gonzalez"
  description: "Developer, Linux and PostgreSQL enthusiast"
  cvLink: "https://drive.google.com/file/d/1494mwC7Z4xxNQSCe8eWHPdJEV-zjr5pw/view?usp=sharing"

pygmentsCodefences: true
pygmentsCodefencesGuessSyntax: true
pygmentsStyle: "vim"

sitemap:
  changefreq: monthly
  filename: sitemap.xml
  priority: 0.5
